<a href="https://colab.research.google.com/github/fist2/Deep-Learning-Pytorch/blob/main/deep_learning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([[4],
                 [5],
                 [6]])

print(a@b)

tensor([32])


In [7]:
import torch
temperature = torch.tensor([[70,72,75], [68,69,40]])
adjustment = torch.tensor([[2,2,2], [2,2,2]])

print(temperature + adjustment)

tensor([[72, 74, 77],
        [70, 71, 42]])


In [8]:
import torch
my_list = torch.tensor([[1,2,3], [4,5,6]])
print(my_list.shape)

torch.Size([2, 3])


In [10]:
import torch.nn as nn
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
linear_layer = nn.Linear(3, 2)
output_tensor = linear_layer(input_tensor)
print(output_tensor)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-0.4156, -0.0906]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.2047, -0.4960, -0.3816],
        [ 0.5069, -0.4228, -0.3149]], requires_grad=True)
Parameter containing:
tensor([-0.2090, -0.1485], requires_grad=True)


In [12]:
import torch.nn as nn
input_tensor = torch.tensor([[2001.00, 1500.00, 1700.00]])
linear_layer = nn.Linear(in_features = 3, out_features=2)
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-1075.3560,    66.2317]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.5593,  0.0713, -0.0372],
        [ 0.2170, -0.0607, -0.1627]], requires_grad=True)
Parameter containing:
tensor([ 0.2482, -0.2698], requires_grad=True)


In [14]:
import torch.nn as nn
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2)
)
total = 0
for parameter in model.parameters():
  total += parameter.numel()
print(total)

46


In [ ]:
from google.colab import drive
drive.mount('/content/drive')