<a href="https://colab.research.google.com/github/fist2/Deep-Learning-Pytorch/blob/main/deep_learning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([[4],
                 [5],
                 [6]])

print(a@b)

tensor([32])


In [7]:
import torch
temperature = torch.tensor([[70,72,75], [68,69,40]])
adjustment = torch.tensor([[2,2,2], [2,2,2]])

print(temperature + adjustment)

tensor([[72, 74, 77],
        [70, 71, 42]])


In [8]:
import torch
my_list = torch.tensor([[1,2,3], [4,5,6]])
print(my_list.shape)

torch.Size([2, 3])


In [10]:
import torch.nn as nn
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
linear_layer = nn.Linear(3, 2)
output_tensor = linear_layer(input_tensor)
print(output_tensor)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-0.4156, -0.0906]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.2047, -0.4960, -0.3816],
        [ 0.5069, -0.4228, -0.3149]], requires_grad=True)
Parameter containing:
tensor([-0.2090, -0.1485], requires_grad=True)


In [12]:
import torch.nn as nn
input_tensor = torch.tensor([[2001.00, 1500.00, 1700.00]])
linear_layer = nn.Linear(in_features = 3, out_features=2)
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-1075.3560,    66.2317]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.5593,  0.0713, -0.0372],
        [ 0.2170, -0.0607, -0.1627]], requires_grad=True)
Parameter containing:
tensor([ 0.2482, -0.2698], requires_grad=True)


In [14]:
import torch.nn as nn
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2)
)
total = 0
for parameter in model.parameters():
  total += parameter.numel()
print(total)

46


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [5]:
import torch
import torch.nn as nn
input_tensor = torch.tensor([[7.0, 8.0, 3.0, 1.5, 8.9, 7.5, 6.0, 5.0]])
model = nn.Sequential(
    nn.Linear(8, 4),
    nn.Linear(4, 2)
)
output = model(input_tensor)
print(output)

tensor([[0.0507, 1.3706]], grad_fn=<AddmmBackward0>)


In [6]:
import torch
import torch.nn as nn
model = nn.Sequential(
    nn.Linear(9,4),
    nn.Linear(4,2),
    nn.Linear(2,1)
)
total = 0
for parameter in model.parameters():
  total += parameter.numel()
print(total)

53


In [7]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)

print(output)

tensor([[0.9975]])


In [11]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[4.0, 0.0, 1.0]])
model = nn.Sequential(
    nn.Linear(3,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)
output = model(input_tensor)

print(output)

tensor([[0.3470]], grad_fn=<SigmoidBackward0>)


In [12]:
import torch
batch_size = 5
features = 4
classes = 3

tensor = torch.randn(batch_size, features, classes)

print(tensor)

tensor([[[-1.7719, -0.0422, -0.3415],
         [-0.8913,  0.2594, -0.0861],
         [ 0.2280,  2.2075,  0.1723],
         [ 0.7564, -1.2730, -0.0308]],

        [[-2.4452, -2.0583,  0.8807],
         [-0.3967,  0.1537,  0.7460],
         [ 0.9583, -1.1186,  0.4197],
         [ 0.9968,  1.2701,  0.4229]],

        [[ 1.7280,  1.0524, -0.7145],
         [ 0.8497,  0.3037, -0.9551],
         [ 0.0219, -0.4610, -2.1180],
         [-0.1146,  0.7041, -0.3503]],

        [[ 0.5964,  0.5157, -0.3929],
         [ 0.1819, -0.3812, -0.7457],
         [ 0.7967, -1.1269, -0.4312],
         [-0.6727,  0.4385, -0.0774]],

        [[ 0.3289, -0.5683, -0.1533],
         [-1.3519, -0.8704, -0.2596],
         [ 1.7571,  0.9743,  0.7970],
         [-0.8655,  1.3151,  1.1233]]])


In [13]:
import torch
import torch.nn as nn

batch_size = 5
features = 4
classes = 3

tensor = torch.randn(batch_size, features, classes)
probabiltities = nn.Softmax(dim=-1)
output = probabiltities(tensor)

print(output)

tensor([[[0.1184, 0.3195, 0.5621],
         [0.0610, 0.4444, 0.4946],
         [0.0863, 0.6226, 0.2911],
         [0.4013, 0.3604, 0.2383]],

        [[0.2024, 0.7144, 0.0832],
         [0.2361, 0.5910, 0.1729],
         [0.2295, 0.6484, 0.1221],
         [0.3054, 0.5140, 0.1806]],

        [[0.1731, 0.4680, 0.3589],
         [0.0177, 0.9710, 0.0113],
         [0.4956, 0.3727, 0.1317],
         [0.3369, 0.1189, 0.5443]],

        [[0.1581, 0.3477, 0.4941],
         [0.3542, 0.2636, 0.3822],
         [0.3062, 0.3708, 0.3230],
         [0.0616, 0.8206, 0.1178]],

        [[0.7195, 0.0772, 0.2032],
         [0.4383, 0.4970, 0.0646],
         [0.0271, 0.3224, 0.6505],
         [0.4940, 0.4091, 0.0969]]])


In [18]:
import torch
import torch.nn as nn

batch_size = 5
features = 4
classes = 3

tensor = torch.randn(batch_size, features, classes)
model = nn.Sequential(
    nn.Linear(classes, 2), # Corrected: in_features should be 'classes' (3)
    nn.Linear(2, classes),
    nn.Softmax(dim=-1)
)
output = model(tensor)
print(output)

tensor([[[0.4056, 0.4651, 0.1293],
         [0.2484, 0.5938, 0.1578],
         [0.3543, 0.4826, 0.1632],
         [0.6160, 0.2738, 0.1102]],

        [[0.1991, 0.6435, 0.1573],
         [0.4376, 0.4043, 0.1581],
         [0.2331, 0.5937, 0.1732],
         [0.6245, 0.1695, 0.2060]],

        [[0.3768, 0.4643, 0.1589],
         [0.3520, 0.4682, 0.1797],
         [0.3624, 0.4289, 0.2086],
         [0.5330, 0.3364, 0.1306]],

        [[0.5524, 0.2604, 0.1872],
         [0.4060, 0.4498, 0.1442],
         [0.3238, 0.5190, 0.1573],
         [0.3819, 0.4053, 0.2127]],

        [[0.4666, 0.3102, 0.2232],
         [0.2861, 0.5183, 0.1956],
         [0.4527, 0.4096, 0.1377],
         [0.5422, 0.3101, 0.1477]]], grad_fn=<SoftmaxBackward0>)
